name: ges
channels:
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - python 3.10
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=12.5
  - ninja
  - pip:
      - pytorch-msssim
      - torchmetrics[image]
      - scikit-learn